### ISSUE TITLE
ImportError: cannot import name 'ADDED_KV_ATTENTION_PROCESSORS'

### ISSUE THREAD

**Issue by chlowden** [thecooltechguy/ComfyUI-MagicAnimate#21]
Hello
Would you have an idea why I am getting the error below when starting up comfy UI with conda please?
Many thanks

`Torch version: 2.0.1+cu117
2024-01-09 09:13:30.296155: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-09 09:13:30.296191: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-09 09:13:30.296204: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
Traceback (most recent call last):
  File "/home/admin/ComfyUI/nodes.py", line 1810, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/admin/ComfyUI/custom_nodes/ComfyUI-MagicAnimate/__init__.py", line 16, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/home/admin/ComfyUI/custom_nodes/ComfyUI-MagicAnimate/nodes.py", line 15, in <module>
    from magicanimate.models.appearance_encoder import AppearanceEncoderModel
  File "/home/admin/ComfyUI/custom_nodes/ComfyUI-MagicAnimate/libs/magicanimate/models/appearance_encoder.py", line 31, in <module>
    from diffusers.models.attention_processor import (
ImportError: cannot import name 'ADDED_KV_ATTENTION_PROCESSORS' from 'diffusers.models.attention_processor' (/home/admin/anaconda3/envs/automatic/lib/python3.10/site-packages/diffusers/models/attention_processor.py)

Cannot import /home/admin/ComfyUI/custom_nodes/ComfyUI-MagicAnimate module for custom nodes: cannot import name 'ADDED_KV_ATTENTION_PROCESSORS' from 'diffusers.models.attention_processor' (/home/admin/anaconda3/envs/automatic/lib/python3.10/site-packages/diffusers/models/attention_processor.py)
---------------------------------`

**Comment by chlowden** [comment]
I think I have found the resolution to this issue ...
I did not have diffusers installed ...
https://github.com/huggingface/diffusers
