### ISSUE TITLE
Currently broken with latest ComfyUI?

### ISSUE THREAD

**Issue by cracklebox** [thecooltechguy/ComfyUI-MagicAnimate#24]
Have tried with fresh installs on multiple machines. Anybody else experiencing simplilar.

```
`Cannot import C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MagicAnimate module for custom nodes: cannot import name 'PositionNet' from 'diffusers.models.embeddings' (C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\embeddings.py)
### Loading: ComfyUI-Manager (V2.7.2)
### ComfyUI Revision: 1965 [f44225fd] | Released on '2024-02-09'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
Traceback (most recent call last):
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ControlNet-LLLite-ComfyUI\\__init__.py'

Cannot import C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ControlNet-LLLite-ComfyUI module for custom nodes: [Errno 2] No such file or directory: 'C:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ControlNet-LLLite-ComfyUI\\__init__.py'

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ControlNet-LLLite-ComfyUI
   0.0 seconds: C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.1 seconds: C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.2 seconds: C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.2 seconds: C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.2 seconds (IMPORT FAILED): C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MagicAnimate
   0.5 seconds: C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux`
```

**Comment by PaulCollingwood** [comment]
delete the _contents_ of the __init__ files as noted in the install instructions.

**Comment by cracklebox** [comment]
I can't see that in the install instructions? I tried anyway, and the issue persists

**Comment by mskiller** [comment]
Hi, I got the same issue, I not see init files, neither here or in install process
I got 2 __init__.py files one in root of ComfyUI-MagicAnimate the second here ComfyUI-MagicAnimate\libs\magicanimate
I have to delete a file or just empty it ?

**Comment by mskiller** [comment]
treid both still the same issue:
custom_nodes\ComfyUI-MagicAnimate module for custom nodes: cannot import name 'PositionNet' from 'diffusers.models.embeddings'
I had my diffusers updated to run Stable Cascade, so everything run smooth, I tried to install thru manager, all dl went good, but then, got the issue that cannot import name 'PositionNet' from 'diffusers.models.embeddings' so comfyui-magicanimate does not load :( hope someone will have a proper answer. Thanks you
