### ISSUE TITLE
ImportError: cannot import name 'PositionNet' from 'diffusers.models.embeddings'

### ISSUE THREAD

**Issue by xllusion-dong** [thecooltechguy/ComfyUI-MagicAnimate#25]
Got error when starting comfyUI

> File "E:\PycharmProjects\ComfyUI\custom_nodes\ComfyUI-MagicAnimate\libs\magicanimate\models\appearance_encoder.py", line 39, in <module>
>     from diffusers.models.embeddings import (
> ImportError: cannot import name 'PositionNet' from 'diffusers.models.embeddings'

There is no PositionNet in diffusers code, how to solve the problem?

**Comment by 1462476229** [comment]
the same problem, how to solve the problem?

**Comment by ja-nina** [comment]
Same problem

**Comment by ja-nina** [comment]
@xllusion-dong @1462476229  thus acctually can be solved by downgrading to diffusers 0.25.1 :), not a long-term fix but certainly gets it working

**Comment by xllusion-dong** [comment]
Good, I will try it.

**Comment by faying** [comment]
Same problem and already check various diffusers versions:
ImportError: cannot import name 'PositionNet' from 'diffusers.models.embeddings' 

Cannot import /root/Yves/ComfyUI/custom_nodes/ComfyUI-MagicAnimate module for custom nodes: cannot import name 'PositionNet' from 'diffusers.models.embeddings'

**Comment by ja-nina** [comment]
@faying yes that happens to me to while on the version mentioned, however i do not need to use PositionNet, so the error does not bother me.

**Comment by xiaochuanyu1978** [comment]
Same problem

** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
VAE dtype: torch.bfloat16

deprecate("UNet2DConditionModel", "0.29", deprecation_message)
Traceback (most recent call last):
  File "C:\SD\ComfyUI\nodes.py", line 1889, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\SD\ComfyUI\custom_nodes\ComfyUI-MagicAnimate\__init__.py", line 16, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\SD\ComfyUI\custom_nodes\ComfyUI-MagicAnimate\nodes.py", line 15, in <module>
    from magicanimate.models.appearance_encoder import AppearanceEncoderModel
  File "C:\SD\ComfyUI\custom_nodes\ComfyUI-MagicAnimate\libs\magicanimate\models\appearance_encoder.py", line 39, in <module>
    from diffusers.models.embeddings import (
ImportError: cannot import name 'PositionNet' from 'diffusers.models.embeddings' (C:\SD\venv\lib\site-packages\diffusers\models\embeddings.py)

![ComfyUI-MagicAnimateIMPORT FAILED](https://github.com/thecooltechguy/ComfyUI-MagicAnimate/assets/19223910/bc43ebd0-2591-481d-bd23-f24b9b09fe88)
![ComfyUI-MagicAnimateIMPORT FAILED2](https://github.com/thecooltechguy/ComfyUI-MagicAnimate/assets/19223910/0cc059c5-c10a-4919-a8cf-27a8c83e04a9)
![ComfyUI-MagicAnimateIMPORT FAILED3](https://github.com/thecooltechguy/ComfyUI-MagicAnimate/assets/19223910/eb527191-58b3-45c0-b159-7c7cf9709335)
![ComfyUI-MagicAnimateIMPORT FAILED4](https://github.com/thecooltechguy/ComfyUI-MagicAnimate/assets/19223910/9bc7e78e-ea7f-4e6b-ab80-3f8a26f1bd15)
