### ISSUE TITLE
ModuleNotFoundError: No module named 'imageio'

### ISSUE THREAD

**Issue by HaeChan-Kwon** [thecooltechguy/ComfyUI-MagicAnimate#29]
C:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-06-30 19:46:40.849712
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: C:\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: C:\ComfyUI_windows_portable\ComfyUI\main.py
** Log path: C:\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MagicAnimate
   0.4 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 10240 MB, total RAM 65349 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 : cudaMallocAsync
Using pytorch cross attention
C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MagicAnimate\__init__.py", line 16, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MagicAnimate\nodes.py", line 17, in <module>
    from magicanimate.pipelines.pipeline_animation import AnimationPipeline
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MagicAnimate\libs\magicanimate\pipelines\pipeline_animation.py", line 63, in <module>
    from magicanimate.utils.util import get_tensor_interpolation_method
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MagicAnimate\libs\magicanimate\utils\util.py", line 9, in <module>
    import imageio
ModuleNotFoundError: No module named 'imageio'

Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MagicAnimate module for custom nodes: No module named 'imageio'
### ComfyUI Revision: 2309 [dbb7dd3b] | Released on '2024-06-30'

Import times for custom nodes:
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.2 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.2 seconds (IMPORT FAILED): C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MagicAnimate

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json

------------------------------------------------------------------------------------------------------------------------------------------------

I am encountering an issue with ComfyUI, and I need help resolving it. Below is the error message I'm receiving

**Comment by HubUserUnknown** [comment]
FOLLOW THE INSTALLATION STEPS IN THE FILE.

WORKING AS OF 05/30/2025 IN WINDOWS 11.

[MagicAnimate_installation_steps.txt](https://github.com/user-attachments/files/20514923/MagicAnimate_installation_steps.txt)
