### ISSUE TITLE
ComfyUI can't load nodes

### ISSUE THREAD

**Issue by yuri-fus** [thecooltechguy/ComfyUI-MagicAnimate#3]
Hi !
I am waiting for such a great tool for years :) But.... The nodes are not loading in ComfyUI.
The ComfyUI is up to date and working fine
The issue is present on Linux and on Win

this is the error from the ubuntu terminal

File "/home/user/ComfyUI/nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/ComfyUI/custom_nodes/ComfyUI-MagicAnimate/__init__.py", line 15, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/home/user/ComfyUI/custom_nodes/ComfyUI-MagicAnimate/nodes.py", line 11, in <module>
    from diffusers import AutoencoderKL, DDIMScheduler, UniPCMultistepScheduler
ImportError: cannot import name 'UniPCMultistepScheduler' from 'diffusers' (/home/user.local/lib/python3.10/site-packages/diffusers/__init__.py)

Cannot import /home/user/ComfyUI/custom_nodes/ComfyUI-MagicAnimate module for custom nodes: cannot import name 'UniPCMultistepScheduler' from 'diffusers' (/home/user/.local/lib/python3.10/site-packages/diffusers/__init__.py)

![image](https://github.com/thecooltechguy/ComfyUI-MagicAnimate/assets/72974298/c62cf9d5-acd0-4c3b-98e7-f1ceeadc65db)

**Comment by yuri-fus** [comment]
Thanks it's working now !

**Comment by jackylee1** [comment]
i have same problem,and it shows i didn't install it ,but i did it

**Comment by jackylee1** [comment]
it is already installed but it shows red errorr,fuck

**Comment by jackylee1** [comment]
![屏幕截图 2023-12-12 161035](https://github.com/thecooltechguy/ComfyUI-MagicAnimate/assets/3367277/70ce959c-3fed-408a-bb31-840b0215e4e8)
![Uploading 屏幕截图 2023-12-12 162217.png…]()

**Comment by jackylee1** [comment]
![屏幕截图 2023-12-12 165033](https://github.com/thecooltechguy/ComfyUI-MagicAnimate/assets/3367277/f99b21f6-10f6-452d-a6ab-11fd7fc9db07)

**Comment by jackylee1** [comment]
Traceback (most recent call last):
  File "D:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MagicAnimate\__init__.py", line 15, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MagicAnimate\nodes.py", line 10, in <module>
    from omegaconf import OmegaConf
ModuleNotFoundError: No module named 'omegaconf'

**Comment by KimiaMaz** [comment]
Same problem
