### ISSUE TITLE
Import failed

### ISSUE THREAD

**Issue by alexdoroga** [thecooltechguy/ComfyUI-MagicAnimate#30]
Traceback (most recent call last):
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MagicAnimate\__init__.py", line 16, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MagicAnimate\nodes.py", line 14, in <module>
    from magicanimate.models.controlnet import ControlNetModel
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MagicAnimate\libs\magicanimate\models\controlnet.py", line 31, in <module>
    from diffusers.models.unet_2d_blocks import (
ModuleNotFoundError: No module named 'diffusers.models.unet_2d_blocks'

**Comment by aurel-g** [comment]
I got around this problem installing `diffusers<0.26.0`

I also had to install some dependencies which are not listed in requirements.txt:

```
huggingface_hub==0.24.3
imageio
accelerate
```
