### ISSUE TITLE
OverflowError: cannot fit 'int' into an index-sized integer

### ISSUE THREAD

**Issue by DorotaLuna** [thecooltechguy/ComfyUI-MagicAnimate#5]
Using the example workflow, 
select model -> 
upload reference image -> 
upload pose video -> 
click queue prompt -> 
when excuting "Magic Animate" node, it boomed

System Win11 with Python 3.10.9

Tried reinstall requirements, upload another image, change some input value, didnt work

> got prompt
control shape: (25, 512, 512, 3)
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\AI\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\AI\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\AI\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-MagicAnimate\nodes.py", line 254, in generate
    sample = pipeline(
  File "C:\AI\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-MagicAnimate\libs\magicanimate\pipelines\pipeline_animation.py", line 591, in __call__
    text_embeddings = self._encode_prompt(
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI-MagicAnimate\libs\magicanimate\pipelines\pipeline_animation.py", line 189, in _encode_prompt
    text_inputs = self.tokenizer(
  File "C:\AI\python_embeded\lib\site-packages\transformers\tokenization_utils_base.py", line 2790, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "C:\AI\python_embeded\lib\site-packages\transformers\tokenization_utils_base.py", line 2876, in _call_one
    return self.batch_encode_plus(
  File "C:\AI\python_embeded\lib\site-packages\transformers\tokenization_utils_base.py", line 3067, in batch_encode_plus
    return self._batch_encode_plus(
  File "C:\AI\python_embeded\lib\site-packages\transformers\tokenization_utils.py", line 807, in _batch_encode_plus
    batch_outputs = self._batch_prepare_for_model(
  File "C:\AI\python_embeded\lib\site-packages\transformers\tokenization_utils.py", line 879, in _batch_prepare_for_model
    batch_outputs = self.pad(
  File "C:\AI\python_embeded\lib\site-packages\transformers\tokenization_utils_base.py", line 3274, in pad
    outputs = self._pad(
  File "C:\AI\python_embeded\lib\site-packages\transformers\tokenization_utils_base.py", line 3638, in _pad
    encoded_inputs["attention_mask"] = encoded_inputs["attention_mask"] + [0] * difference
OverflowError: cannot fit 'int' into an index-sized integer

Prompt executed in 0.25 seconds

**Comment by AnkilP** [comment]
I'm seeing the same issue but with rgthree

```
May 29 05:14:46 f23eda6b-fab6-482b-8c4a-80057980004c python3[6007]:   File "/home/user/ComfyUI/execution.py", line 385, in <lambda>
May 29 05:14:46 f23eda6b-fab6-482b-8c4a-80057980004c python3[6007]:     to_execute = sorted(list(map(lambda a: (len(recursive_will_execute(prompt, self.outputs, a[-1], memo)), a[-1]), to_execute)))
May 29 05:14:46 f23eda6b-fab6-482b-8c4a-80057980004c python3[6007]:                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 29 05:14:46 f23eda6b-fab6-482b-8c4a-80057980004c python3[6007]:   File "/home/user/ComfyUI/custom_nodes/rgthree-comfy/__init__.py", line 242, in rgthree_recursive_will_execute
May 29 05:14:46 f23eda6b-fab6-482b-8c4a-80057980004c python3[6007]:     will_execute_value = execution.recursive_will_execute(prompt, outputs, input_unique_id,
May 29 05:14:46 f23eda6b-fab6-482b-8c4a-80057980004c python3[6007]:                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 29 05:14:46 f23eda6b-fab6-482b-8c4a-80057980004c python3[6007]:   File "/home/user/ComfyUI/custom_nodes/rgthree-comfy/__init__.py", line 246, in rgthree_recursive_will_execute
May 29 05:14:46 f23eda6b-fab6-482b-8c4a-80057980004c python3[6007]:     will_execute.add(len(will_execute_value))
May 29 05:14:46 f23eda6b-fab6-482b-8c4a-80057980004c python3[6007]:                      ^^^^^^^^^^^^^^^^^^^^^^^
May 29 05:14:46 f23eda6b-fab6-482b-8c4a-80057980004c python3[6007]: OverflowError: cannot fit 'int' into an index-sized integer
```

**Comment by AnkilP** [comment]
@DorotaLuna - how did you fix this?

**Comment by DorotaLuna** [comment]
> @DorotaLuna - how did you fix this?

aint fix it, i just dont use it anymore, 
use animateanyone or musepose
